// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_DEVICE_CONFIG__SIZE		29066

// Variables
extern uint8_t data_device_config_[];

// CONFXML_H_
#endif
